languageCode = "en"
languageName = "English"
weight = 1
title = "Andy Pindus"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "AP-logo.png"
description = "Andy Pindus"
secondaryLogo = "AP-logo-dark.png"

[author]
name = "Andy Pindus"
image = "AI_Andy.jpg"
headline = "Technology Leader | Cloud, DevOps & GenAI Consultant | IT Strategy & Optimization"
links = [
     { email = "mailto:pindus.andy@gmail.com" },
     { linkedin = "https://www.linkedin.com/in/andypindus/" },
]
